name: Build & Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - "**"
    branches:
      - temp-integration

jobs:
  server-docker:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: server
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm run prisma:generate

      - name: Check formatting
        run: npm run prettier

      - name: Build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v4
        with:
          context: ./server
          tags: hicsail/fhs-server:staging
          build-args: DATABASE_URL_DOCKER=${{ secrets.DATABASE_URL_DOCKER }}

  client-docker:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: client
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run prettier

      - name: Build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v4
        with:
          context: ./client
          tags: hicsail/fhs-client:staging

  deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/temp-integration'
    needs: [server-docker, client-docker]
    steps:
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true
